name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    environment:
      TZ: "/usr/share/zoneinfo/your/location"
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ runner.os }}-coverage-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-coverage-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          out-type: Lcov
          args: '--all-features -- --test-threads 1'
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v1
        with:
          fail_ci_if_error:     true